import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link
          rel="preload"
          href="/assets/fonts/BasementGrotesque-Black_v1.202.otf"
          as="font"
          crossOrigin=""
        />
        <style>{`
        
@font-face {
  font-family: "Basement Grotesque";
  src: url("/assets/fonts/BasementGrotesque-Black_v1.202.otf")
    format("opentype");
  font-weight: 900;
  font-style: normal;
  font-display: swap;
}
@font-face {
  font-family: "Basement Grotesque";
  src: url("/assets/fonts/BasementGrotesque-Black_v1.202.otf")
    format("opentype");
  font-weight: 800;
  font-style: normal;
  font-display: swap;
}
@font-face {
  font-family: "Basement Grotesque";
  src: url("/assets/fonts/BasementGrotesque-Black_v1.202.otf")
    format("opentype");
  font-weight: 700;
  font-style: normal;
  font-display: swap;
}
@font-face {
  font-family: "Basement Grotesque";
  src: url("/assets/fonts/BasementGrotesque-Black_v1.202.otf")
    format("opentype");
  font-weight: 600;
  font-style: normal;
  font-display: swap;
}
@font-face {
  font-family: "Basement Grotesque";
  src: url("/assets/fonts/BasementGrotesque-Black_v1.202.otf")
    format("opentype");
  font-weight: 500;
  font-style: normal;
  font-display: swap;
}
@font-face {
  font-family: "Basement Grotesque";
  src: url("/assets/fonts/BasementGrotesque-Black_v1.202.otf")
    format("opentype");
  font-weight: 400;
  font-style: normal;
  font-display: swap;
}
@font-face {
  font-family: "Basement Grotesque";
  src: url("/assets/fonts/BasementGrotesque-Black_v1.202.otf")
    format("opentype");
  font-weight: 300;
  font-style: normal;
  font-display: swap;
}

    `}</style>
      </Head>
      <body className="">{children}</body>
    </html>
  );
}
